### ISSUE TITLE
What is the Status of Authdog?

### ISSUE THREAD

**Issue by rohanbam** [authdog/http-headers-check#86]
Hi, I came across your blog https://fauna.com/blog/building-an-authentication-saas-with-faunadb and found your project interesting. I wanted to know when authdog will be publicly available and also any available details regarding pricing, licensing etc...  I'm not sure that this is the right place to ask but I couldn't find any other way to contact you. Please let me know if there is a more appropriate forum for questions regarding authdog. Thank you. Cheers.

**Comment by dbrrt** [comment]
@rohanbam Thanks for your message. Can you send an email to david@authdog.com, I can give you there the development/deployment status and all the details.
